
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    container_name: secret-password-backend
    networks:
      - app-network


  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 80:5000
    container_name: secret-password-frontend
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
