
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    container_name: secret-password-backend

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    container_name: secret-password-frontend
    depends_on:
      - backend
